site_name: No Bullshit Guide to Statistics
plugins:
  - mkdocs-jupyter
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: material
nav:
  - Home: README.md
  - Chapter 1:
      - Data Overview: notebooks/10_DATA.md
      - Intro to Data: notebooks/11_intro_to_data.ipynb
      - Data in Practice: notebooks/12_data_in_practice.ipynb
      - Descriptive Statistics: notebooks/13_descriptive_statistics.ipynb
  - Chapter 2:
      - Probability Theory: notebooks/20_PROB.md
      - Discrete Random Variables: notebooks/21_discrete_random_vars.ipynb
      - Multiple Random Variables: notebooks/22_multiple_random_vars.ipynb
      - Inventory of Discrete Distributions: notebooks/23_inventory_discrete_dists.ipynb
      - Calculus Prerequisites: notebooks/24_calculus_prerequisites.ipynb
      - Continuous Random Variables: notebooks/25_continuous_random_vars.ipynb
      - Inventory of Continuous Distributions: notebooks/26_inventory_continuous_dists.ipynb
      - Random Variable Generation: notebooks/27_random_var_generation.ipynb
      - Probability Models for Random Samples: notebooks/28_random_samples.ipynb
  - Chapter 3:
      - Inferential Statistics: notebooks/30_STATS.md
      - Estimates and Estimators: notebooks/31_estimators.ipynb
      - Confidence Intervals: notebooks/32_confidence_intervals.ipynb
      - Introduction to Hypothesis Testing: notebooks/33_intro_to_NHST.ipynb
      - Part 1 Analtyic Approximations: notebooks/34_analytical_approx.ipynb
      - Part 2 Analytic Approximations: notebooks/OLD34_analytical_approximation.ipynb
      - Two-sample tests: notebooks/35_two_sample_tests.ipynb
      - Statistical Design and Error Analysis: notebooks/36_design.ipynb
      - Inventory of Statistical Tests: notebooks/37_inventory_stats_tests.ipynb
  - Chapter 4:
      - Linear Models: notebooks/40_LINEAR_MODELS.md
      - Simple Linear Regression: notebook/41_simple_linear_regression.ipynb
      - Multiple Linear Regression: notebook/42_multiple_linear_regression.ipynb
      - Interpreting Linear Models: notebook/43_interpreting_linear_models.ipynb
      - Regression with Categorical Predictors: notebooks/44_regression_with_categorical_predictors.ipynb
      - Causal Inference using Linear Models: notebooks/45_causal_inference.ipynb
      - Generalized Linear Models: notebooks/46_generalized_linear_models.ipynb
      - Bonus Section: notebooks/40_extra_cut_material.ipynb
  - Chapter 5:
      - Bayesian Statistics: notebooks/50_BAYESIAN_STATS.md
      - Introduction to Bayesian Statistics: notebooks/51_intro_to_Bayesian_stats.ipynb
      - Bayesian Inference Computations: notebooks/52_Bayesian_inference_computations.ipynb
      - Bayesian Linear Models: notebooks/53_Bayesian_linear_models.ipynb
      - Bayesian Difference Between Means: notebooks/54_difference_between_means.ipynb
      - Hierarchical Models: notebooks/55_hierarchical_models.ipynb
  - Appendix:
      - Appendix List: tutorials/appendix.md
      - Cut Material: tutorials/cut_material.ipynb
      - Pandas Tutorial: tutorials/pandas_tutorial.ipynb
      - Python Tutorial: tutorials/python_tutorial.ipynb
      - Mean Code Estimation: notebooks/99_mean_estimation_details.ipynb
      - Proportions Estimators: notebooks/99_proportions_estimators.ipynb
      - Seaborn Tutorial: tutorials/seaborn_tutorial.ipynb