site_name: No Bullshit Guide to Statistics
docs_dir: "docs"
site_dir: "_build/html/site"
site_url: "https://nobsstats.com/site/"
site_author: Ivan Savov
plugins:
  - mkdocs-jupyter:
      include_source: True
extra_javascript:
  - javascripts/mathjax_config.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: false
theme:
  name: material
exclude_docs: |
  notebooks/explorations
nav:
  - Home: index.md
  - Chapter 1:
      - Data: notebooks/10_DATA.md
      - Introduction to data: notebooks/11_intro_to_data.ipynb
      - Data in practice: notebooks/12_data_in_practice.ipynb
      - Descriptive dtatistics: notebooks/13_descriptive_statistics.ipynb
  - Chapter 2:
      - Probability theory: notebooks/20_PROB.md
      - Discrete random variables: notebooks/21_discrete_random_vars.ipynb
      - Multiple random variables: notebooks/22_multiple_random_vars.ipynb
      - Inventory of discrete distributions: notebooks/23_inventory_discrete_dists.ipynb
      - Continuous random variables: notebooks/24_continuous_random_vars.ipynb
      - Multiple continuous random variables: notebooks/25_multiple_continuous_random_vars.ipynb
      - Inventory of continuous distributions: notebooks/26_inventory_continuous_dists.ipynb
      - Simulations and empirical distributions: notebooks/27_simulations.ipynb
      - Probability models for random samples: notebooks/28_random_samples.ipynb
  - Chapter 3:
      - Inferential statistics: notebooks/30_STATS.md
      - Estimates and estimators: notebooks/31_estimators.ipynb
      - Confidence intervals: notebooks/32_confidence_intervals.ipynb
      - Introduction to hypothesis testing: notebooks/33_intro_to_NHST.ipynb
      - Analytical approximations: notebooks/34_analytical_approx.ipynb
      - Two-sample tests: notebooks/35_two_sample_tests.ipynb
      - Statistical design and error analysis: notebooks/36_design.ipynb
      - Inventory of statistical tests: notebooks/37_inventory_stats_tests.ipynb
  - Chapter 4:
      - Linear models: notebooks/40_LINEAR_MODELS.md
      - Simple linear regression: notebook/41_simple_linear_regression.ipynb
      - Multiple linear regression: notebook/42_multiple_linear_regression.ipynb
      - Interpreting linear models: notebook/43_interpreting_linear_models.ipynb
      - Regression with categorical predictors: notebooks/44_regression_with_categorical_predictors.ipynb
      - Causal inference using linear models: notebooks/45_causal_inference.ipynb
      - Generalized linear models: notebooks/46_generalized_linear_models.ipynb
  - Chapter 5:
      - Bayesian statistics: notebooks/50_BAYESIAN_STATS.md
      - Introduction to Bayesian statistics: notebooks/51_intro_to_Bayesian_stats.ipynb
      - Bayesian inference computations: notebooks/52_Bayesian_inference_computations.ipynb
      - Bayesian linear models: notebooks/53_Bayesian_linear_models.ipynb
      - Bayesian difference between means: notebooks/54_difference_between_means.ipynb
      - Hierarchical models: notebooks/55_hierarchical_models.ipynb
  - Appendix:
      - Appendices: tutorials/appendix.md
      - Python tutorial: tutorials/python_tutorial.ipynb
      - Pandas tutorial: tutorials/pandas_tutorial.ipynb
      - Seaborn tutorial: tutorials/seaborn_tutorial.ipynb
  - Notebooks for blog posts:
      - Index: blogposts/index.md
      - Python coding skills for statistic: blogposts/python_for_stats.ipynb
      - Using Python for probability calculations: blogposts/probability_models.ipynb
      - Understanding sampling distributions: blogposts/sampling_distributions.ipynb
      - Bootstrap estimation of uncertainty: blogposts/bootstrap.ipynb
      - Hypothesis testing using simulation: blogposts/simulation_hypothesis_tests.ipynb
      - The permutation test for comparing two groups: blogposts/permutation_test.ipynb
      - Statistical procedures as Python code: blogposts/stats_procedures.ipynb
      - Python libraries for doing statistics: blogposts/python_stats_libraries.ipynb
