#!/bin/bash

# Create the JupyterLab settings directory if it doesn't exist
mkdir -p "${HOME}/.jupyter/lab/user-settings/@jupyterlab/apputils-extension"

# Write override settings to disable announcements
cat <<EOF > "${HOME}/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/notification.jupyterlab-settings"
{
  "fetchNews": false
}
EOF

# Disable cookie consent popup in JupyterLab
cat <<EOF > "${HOME}/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/privacy.jupyterlab-settings"
{
  "privacyConsent": {
    "version": 1,
    "accepted": true
  }
}
EOF
