#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : No BS Stats Notebooks
author                      : Ivan Savov
copyright                   : "2024"
logo                        : logo.png
exclude_patterns            : [venv, _build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints",
                               "README.md",
                               "data_generation", "figures_generation",
                               "notebooks/explorations", "notebooks/drafts"]


# MyST parser options
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - colon_fence
    - linkify

sphinx:
  config:
    html_extra_path: ['webrootextra']

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: noBSstats_notebooks.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - noBSstats.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/minireference/noBSstats
  path_to_book: .
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true


# BinderHub to make things interactive
launch_buttons:
  binderhub_url: "https://mybinder.org"
  notebook_interface: "jupyterlab"
  thebe: true


# sphinx:
#   extra_extensions:
#    - sphinx.ext.imgmath
